
# Your GitHub Actions workflow file here
name: Deploy App to Firebase Hosting
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "lib/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      # use this if you need generate build_runner related files
      - run: flutter run build_runner build --delete-conflicting-outputs
      - run: flutter build web --source-maps --web-renderer=canvaskit
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_THE_CRANE_SERVICE_ACCOUNT }}'  
          projectId: '${{ secrets.FIREBASE_THE_CRANE_PROJECT_ID }}'
          target: YOUR_DEPLOYMENT_TARGET
